// packages/vue/src/parts/current-swatch.tsx
import { defineComponent, ref, watch } from "vue";
import { usePicker, usePickerContext } from "../context";
import { bool } from "../props";
import { safeCssValue } from "@colorshot/core";

/** The current value. Clicking copies it as CSS. */
export const CurrentSwatch = /* @__PURE__ */ defineComponent({
  name: "PickerCurrentSwatch",
  props: {
    /** split the swatch: the value the picker opened with on the left (click it to restore), the current one on the right */
    compare: /* @__PURE__ */ bool(),
  },
  setup(props) {
    const ctx = usePickerContext();
    const { store, notify } = ctx;
    const value = usePicker((s) => s.value);
    const mode = usePicker((s) => s.mode);
    const original = value.value;
    // switching modes morphs the swatch: the new value grows out of the old one
    const morph = ref<{ from: string; run: number } | null>(null);
    let last = value.value;
    watch(
      [mode, value],
      ([m, v], [prevMode]) => {
        if (m !== prevMode) morph.value = { from: last, run: (morph.value?.run ?? 0) + 1 };
        last = v;
      },
      { flush: "sync" },
    );
    const copy = () =>
      navigator.clipboard?.writeText(store.getState().value).then(
        () => notify(ctx.labels.copied),
        () => {},
      );
    return () => {
      const labels = ctx.labels;
      const v = value.value;
      const split = props.compare && original !== v;
      return (
        <div data-part="current" data-compare={split ? "" : undefined}>
          {split ? (
            <button
              type="button"
              data-part="current-original"
              aria-label={labels.original}
              data-tooltip={labels.original}
              style={{ "--_cs-swatch": safeCssValue(original) }}
              onClick={() => {
                store.setCss(original);
                store.commit();
              }}
            />
          ) : null}
          <button
            type="button"
            data-part="current-value"
            aria-label={`${labels.copy}: ${v}`}
            data-tooltip={labels.copy}
            style={{ "--_cs-swatch": safeCssValue(morph.value ? morph.value.from : v) }}
            onClick={copy}
          >
            {morph.value ? (
              <span
                key={morph.value.run}
                data-part="current-morph"
                style={{ "--_cs-swatch": safeCssValue(v) }}
                onAnimationend={() => (morph.value = null)}
                aria-hidden="true"
              />
            ) : null}
          </button>
        </div>
      );
    };
  },
});

// packages/react/src/parts/current-swatch.tsx
import { memo, useRef, useState, type CSSProperties } from "react";
import { useIsoLayoutEffect, usePicker, usePickerContext } from "../context";
import { safeCssValue } from "@colorshot/core";

export interface CurrentSwatchProps {
  className?: string;
  style?: CSSProperties;
  /** split the swatch: the value the picker opened with on the left (click it to restore), the current one on the right */
  compare?: boolean;
}

/** The current value. Clicking copies it as CSS. */
export const CurrentSwatch = /* @__PURE__ */ memo(function CurrentSwatch({ className, style, compare }: CurrentSwatchProps) {
  const { store, labels, notify } = usePickerContext();
  const value = usePicker((s) => s.value);
  const mode = usePicker((s) => s.mode);
  const original = useRef(value);
  // switching modes morphs the swatch: the new value grows out of the old one
  const last = useRef({ mode, value });
  const [morph, setMorph] = useState<{ from: string; run: number } | null>(null);
  useIsoLayoutEffect(() => {
    if (last.current.mode !== mode) {
      const from = last.current.value;
      setMorph((m) => ({ from, run: (m?.run ?? 0) + 1 }));
    }
    last.current = { mode, value };
  }, [mode, value]);
  const changed = original.current !== value;
  const copy = () =>
    navigator.clipboard?.writeText(store.getState().value).then(
      () => notify(labels.copied),
      () => {},
    );
  return (
    <div data-part="current" data-compare={compare && changed ? "" : undefined} className={className} style={style}>
      {compare && changed && (
        <button
          type="button"
          data-part="current-original"
          aria-label={labels.original}
          data-tooltip={labels.original}
          style={{ "--_cs-swatch": safeCssValue(original.current) } as CSSProperties}
          onClick={() => {
            store.setCss(original.current);
            store.commit();
          }}
        />
      )}
      <button
        type="button"
        data-part="current-value"
        aria-label={`${labels.copy}: ${value}`}
        data-tooltip={labels.copy}
        style={{ "--_cs-swatch": safeCssValue(morph ? morph.from : value) } as CSSProperties}
        onClick={copy}
      >
        {morph && (
          <span
            key={morph.run}
            data-part="current-morph"
            style={{ "--_cs-swatch": safeCssValue(value) } as CSSProperties}
            onAnimationEnd={() => setMorph(null)}
            aria-hidden
          />
        )}
      </button>
    </div>
  );
});
