// packages/vue/src/parts/preview.tsx
import { defineComponent } from "vue";
import { usePicker, usePickerContext } from "../context";
import { bool } from "../props";
import { safeCssValue } from "@colorshot/core";

/** The current value on a checkerboard. With `compare`, a before / after pair. */
export const Preview = /* @__PURE__ */ defineComponent({
  name: "PickerPreview",
  props: {
    /** also show the value the picker opened with; clicking it restores that value */
    compare: /* @__PURE__ */ bool(),
  },
  setup(props) {
    const ctx = usePickerContext();
    const { store } = ctx;
    const value = usePicker((s) => s.value);
    const original = value.value;
    return () => (
      <div data-part="preview">
        {props.compare ? (
          <button
            type="button"
            data-part="preview-swatch"
            data-checker=""
            data-original=""
            title={ctx.labels.original}
            aria-label={ctx.labels.original}
            style={{ "--_cs-swatch": safeCssValue(original) }}
            onClick={() => {
              store.setCss(original);
              store.commit();
            }}
          />
        ) : null}
        <div data-part="preview-swatch" data-checker="" style={{ "--_cs-swatch": safeCssValue(value.value) }} />
      </div>
    );
  },
});

// packages/react/src/parts/preview.tsx
import { memo, useRef, type CSSProperties, type HTMLAttributes } from "react";
import { usePicker, usePickerContext } from "../context";
import { safeCssValue } from "@colorshot/core";

export interface PreviewProps extends Omit<HTMLAttributes<HTMLDivElement>, "children"> {
  className?: string;
  style?: CSSProperties;
  /** also show the value the picker opened with; clicking it restores that value */
  compare?: boolean;
}

/** The current value on a checkerboard. With `compare`, a before / after pair. */
export const Preview = /* @__PURE__ */ memo(function Preview({ className, style, compare, ...rest }: PreviewProps) {
  const { store, labels } = usePickerContext();
  const value = usePicker((s) => s.value);
  const original = useRef(value);
  return (
    <div data-part="preview" className={className} style={style} {...rest}>
      {compare && (
        <button
          type="button"
          data-part="preview-swatch"
          data-checker=""
          data-original=""
          title={labels.original}
          aria-label={labels.original}
          style={{ "--_cs-swatch": safeCssValue(original.current) } as CSSProperties}
          onClick={() => {
            store.setCss(original.current);
            store.commit();
          }}
        />
      )}
      <div data-part="preview-swatch" data-checker="" style={{ "--_cs-swatch": safeCssValue(value) } as CSSProperties} />
    </div>
  );
});
